#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

scheduler-docker-local-post-app-clone-setup() {
  declare desc="removes docker-local files when setting up a clone"
  declare OLD_APP="$1" NEW_APP="$2"
  local APP_DIR="$DOKKU_ROOT/$NEW_APP"

  rm -rf "$APP_DIR/CONTAINER.*"
}

scheduler-docker-local-post-app-clone-setup "$@"
